spring:
  datasource:
    url: jdbc:postgresql://prod-host:5432/rsl_system
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org.springframework.security: WARN
    org.hibernate: WARN
    com.rslsystem.api: INFO
    root: WARN

# CORS para produção
cors:
  allowed-origins:
    - "https://rsl-system.com"
