spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rsl_system
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    com.rslsystem.api: DEBUG

# CORS para desenvolvimento
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
