spring:
  application:
    name: rsl-system-api
  profiles:
    active: dev 

server:
  port: 8080

rsl:
  system:
    name: "RSL System API"
    version: "0.0.1"
    description: "API do RSL System"
